name: Build and deploy SPA to Azure Web App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'       # or whatever version you need

      - name: Install dependencies
        run: npm ci

      - name: Build production assets
        run: npm run build       # this generates your `dist/` folder

      - name: Copy web.config into dist
        run: copy web.config dist\web.config

      - name: Upload dist as artifact
        uses: actions/upload-artifact@v4
        with:
          name: spa-dist
          path: dist/             # ✅ only upload the built files

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: spa-dist

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id:     ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id:     ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name:       'FirstTry'
          slot-name:      'Production'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package:        './spa-dist'   # ✅ deploy only the dist folder
